[package]
authors = [
    "Anthony DiMarco <ocramida@gmail.com>",
    "Jimmy Cuadra <jimmy@jimmycuadra.com>",
    "Matthew Mayer <matthewkmayer@gmail.com>",
    "Nikita Pekin <contact@nikitapek.in>"
]
build = "build.rs"
description = "AWS SDK for Rust - Core"
documentation = "http://rusoto.github.io/rusoto/rusoto/index.html"
keywords = ["AWS", "Amazon"]
license = "MIT"
name = "rusoto_core"
readme = "README.md"
repository = "https://github.com/rusoto/rusoto"
version = "0.28.0"
homepage = "https://www.rusoto.org/"

[badges]
travis-ci = { repository = "rusoto/rusoto", branch = "master" }
appveyor = { repository = "rusoto/rusoto", branch = "master" }

[build-dependencies]
rustc_version = "0.2.1"

[dependencies]
hyper = "0.10.0"
hyper-native-tls = "0.2.1"
lazy_static = "0.2.1"
log = "0.3.6"
rustc-serialize = "0.3.19"
serde = "1.0.2"
serde_derive = "1.0.2"
time = "0.1.35"
url = "1.2.0"
xml-rs = "0.6"
hmac = "0.5.0"
sha2 = "*"

[dependencies.rusoto_credential]
path = "../credential"
version = "0.8.0"

[dependencies.clippy]
optional = true
version = "0.0"

[dev-dependencies]
env_logger = "0.4.0"
rand = "^0.3.14"
serde_json = "1.0.1"

[features]
nightly-testing = ["clippy", "rusoto_credential/nightly-testing"]
unstable = []
